E_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('customer/', include('customer.urls')),
    path('seller/', include('seller.urls')),
    
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

common/urls.py
from django.urls import path
from . import views
app_name='common'
urlpatterns = [
    path('home',views.home, name='home'),
    path('customer_reg',views.customer_reg),
    path('seller_reg',views.seller_reg),
    path('customer_login',views.customer_login, name='customer_login'),
    path('seller_login',views.seller_login,name='seller_login'),
    path('email_exist',views.email_exist, name='email_exist'),

]

customer/urls.py
from django.urls import path
from . import views

app_name = "customer"

urlpatterns = [
    path('home',views.home, name="home"),
    path('product_details/<int:pid>',views.product_details, name="product_details"),
    path('my_cart',views.my_cart),
    path('my_order',views.my_order),
    path('change_password',views.change_password , name='change_pass'),
    path('profile',views.profile),
    path('logout',views.logout),
    path('remove_item/<int:pid>',views.remove_item,name='remove_item'),
]

customer/models.py
from django.db import models
from seller.models import Product
from common.models import Customer

# Create your models here.
class Cart(models.Model):
    product_details = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

customer/views.py
from django.shortcuts import render,redirect
from seller.models import Product
from common.models import Customer
from customer.models import Cart


# Create your views here.
def home(request):
    product_list = Product.objects.all()
    return render(request,'customertemplates/home.html',{'products':product_list})

def product_details(request,pid):
    msg = ''
    product_details = Product.objects.get(id = pid)

    if request.method == "POST":
        product_exist = Cart.objects.filter(product_details = pid,customer = request.session['customer']).exists()
        if not product_exist:
            cart = Cart(customer_id = request.session['customer'], product_details_id = pid)
            cart.save()
        else:
            msg = "item already in cart"
    context ={
            'details':product_details,
            'msg': msg
    }
    return render(request,'customertemplates/product_details.html',context)
    # return render(request,'customertemplates/product_details.html',{'details':product_details})

def my_cart(request):
    cart = Cart.objects.filter(customer = request.session['customer'])
    return render(request,'customertemplates/my_cart.html',{'customer_cart' : cart})

def my_order(request):
    return render(request,'customertemplates/my_order.html')

def change_password(request):
    msg = ''
    if request.method == 'POST':
        customer = Customer.objects.get(id = request.session['customer'])

        current_pass = request.POST['crnt_pswrd']
        new_pass = request.POST['new_pswrd']
        confirm_pass = request.POST['cnfrm_pswrd']

        if customer.Customer_password == current_pass:
            if new_pass == confirm_pass:
                customer.Customer_password = new_pass
                customer.save()
                msg = 'password changed successfully'
            else:
                msg = 'password does not match'
        else:
            msg = 'incorrect password'
            
    return render(request,'customertemplates/change_password.html',{'msg':msg})



def profile(request):
    cust_prof = Customer.objects.get(id = request.session['customer'])
    return render(request,'customertemplates/profile.html',{'profile':cust_prof})



def logout(request):
    return render(request,'customertemplates/logout.html')



def remove_item(request,pid):
    cart_item = Cart.objects.get(product = pid,Customer = request.session['customer'])
    cart_item.delete()
    return redirect('customer:my_cart')



def logout(request):
    del request.session['customer']
    request.session.flush() # to remove session data from django session table
    return redirect('common:customer_login')

customer/templates/customertemplates/change_password.html
{% extends 'commontemplates/common_master.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
<div class="container pt-5 pb-5">
    <div class="row">
        <div class="col-lg-12">
            <form method="POST">
                {% csrf_token %}
            
            <div class="card shadow border">
                <div class="card-body">
                    <h3>CHANGE PASSWORD</h3>
                    <form>
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Cureent Password</label>
                        <input type="password" class="form-control" id="exampleFormControlInput1" name="crnt_pswrd">
                    </div><br />
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">New Password</label>
                        <input type="password" class="form-control" id="exampleFormControlInput1" name="new_pswrd">
                    </div><br />
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Confirm Password</label>
                        <input type="password" class="form-control" id="exampleFormControlInput1" name="cnfrm_pswrd">
                    </div><br />
                    
                    <button class="btn-btn">submit</button>
                    {{msg}}
                    </form>
                </div>        
            </div>
        </div>
    </div>
</div>
{% endblock %}

</body>
</html>

customer/templates/customertemplates/home.html
{% extends 'commontemplates/common_master.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/pswrd.css' %}">
        <div class="row">
            {% for products in products %}
            <div class="col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{products.product_image.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{products.product_name|title}}</h5>
                      <p class="card-text">{{products.product_description}}</p>
                      <a href="{% url 'customer:product_details' products.id %}" class="btn btn-primary">Go somewhere</a>
                      <p>seller:{{products.Seller.seller_name |title}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
                

{% endblock %}

customer/templates/customertemplates/my_cart.html
{% extends 'commontemplates/common_master.html' %}
{% load static %}
{% block content %}

<table class="table table-striped">
  {% if cart_list %}
    <tr>
        <th>Product Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>image</th>

    </tr>
    {% for cart in customer_cart %}
    <tr class=" table-active">

      <td>{{cart.product_details.product_name}}</td>
      <td>{{cart.product_details.product_description}}</td>
      <td>{{cart.product_details.price}}</td>
      <td>Remove</td>
      <td><a href="{% url 'customer:remove_item' cart.product.id %}">Remove</a></td>
      <td><img src="{{cart.product_details.product_image.url}}" alt=""></td>
    </tr>
    {% endfor %}    
  </table>
  {% else %}
  <h1>Cart Empty</h1>
  {% endif %}
  </div>




{% endblock %}

customer/templates/customertemplates/my_order.html
{% extends 'commontemplates/common_master.html' %}
{% load static %}
{% block content %}

<table class="table table-striped">
    <tr>
        <th>S.no</th>
        <th>Product Name</th>
        <th>Description</th>
        <th>Quantity</th>
        <th>Price</th>
        <th> Order Status</th>
    </tr>
  </table>


         
{% endblock %}

customer/templates/customertemplates/product_details.html
{% extends 'commontemplates/common_master.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/pswrd.css' %}">
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="cataloges">
                    <div class="catalog-2">
                        <img src="{{details.product_image.url}}" alt="">
                        <form method="POST">
                            {% csrf_token %}
                        <h4>name:{{details.product_name}}</h4>
                        <p>product description:{{details.product_description}}</p>
                        <p>price:{{details.price}}</p>
                        <button type="submit" class="btn btn-primary">ADD TO CART</button>
                        {{msg}}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

customer/templates/customertemplates/profile.html
{% extends 'commontemplates/common_master.html' %}
{% load static %}
{% block content %}

<div>
    <img src="{% static 'images/prof.png' %}" alt="" width="400px" height="500px">

    <p>Name: {{profile.customer_name}}</p>
    <p>E-mail: {{profile.customer_email}}</p>
    <p>Phone: {{profile.customer_number}}</p>
    <p>Address: {{profile.customer_address}}</p>
    <p>Gender {{profile.customer_gender}}</p>
</div>


         
{% endblock %}