E_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('customer/', include('customer.urls')),
    path('seller/', include('seller.urls')),
    
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

common/urls.py
from django.urls import path
from . import views
app_name='common'
urlpatterns = [
    path('home',views.home, name='home'),
    path('customer_reg',views.customer_reg),
    path('seller_reg',views.seller_reg),
    path('customer_login',views.customer_login, name='customer_login'),
    path('seller_login',views.seller_login,name='seller_login'),
    path('email_exist',views.email_exist, name='email_exist'),

]

ecom_admin/urls.py
from django.urls import path
from . import views
app_name = 'ecom_admin'
urlpatterns = [
    path('home',views.home),
    path('approve_seller',views.approve_seller, name= 'approve_seller'),
    path('view_seller',views.view_seller, name = 'view_seller'),
    path('view_customer',views.view_customer, name = 'view_customer'),
    path('approve_customer',views.approve_customer, name = 'approve_customer'),
]

ecom_admin/models.py
from django.db import models

# Create your models here.

ecom_admin/views.py
from django.shortcuts import render
from common.models import Customer,Seller
# Create your views here.
def home(request):
    return render(request,'admintemplates/home.html')

def approve_seller(request):
    seller = Seller.objects.all()
    return render(request,'admintemplates/approve_seller.html',{"seller_list":seller})


def view_seller(request):
    return render(request,'admintemplates/view_seller.html')


def view_customer(request):
    return render(request,'admintemplates/view_customer.html')

    
def approve_customer(request):
    Customers = Customer.objects.all()
    return render(request,'admintemplates/approve_customer.html',{"customer_list":Customers})

ecom_admin/templates/admintemplates/approve_customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>approve_cust</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

    <div class="text-center p-4">
        <h1>APPROVE CUSTOMER</h1>
    </div>
<div class="container">
    <div class="row">
        
        <div class="">
            <table class="table">
                <thead>
                <th>Full Name</th>
                <th>Email</th>
                <th>Username</th>
                <th>Phone Number</th>
                <th>Address</th>
                <th>Gender</th>
                <th>Password</th>
                <th>Status</th>
                <th>Remove</th>
                </thead>
                <tbody>
                    {% for customer in customer_list %}
                <tr class="table-active">
                  <td>{{customer.Customer_name|upper}}</td>
                  <td>{{customer.Customer_number}}</td>
                  <td>{{customer.Customer_address}}</td>
                  <td>{{customer.Customer_password}}</td>
                  <td>{{customer.Customer_gender}}</td>
                  <td>{{customer.Customer_email}}</td>
               
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>
</body>
</html>

ecom_admin/templates/admintemplates/approve_seller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>approve_seller</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="text-center p-4">
        <h1>APPROVE CUSTOMER</h1>
    </div>
<div class="container">
    <div class="row">
        
        <div class="">
            <table class="table">
                <thead>
                <th>Seller Name</th>
                <th>Address</th>
                <th>Phone Number</th>
                <th>Email</th>
                <th>Company Name</th>
                <th>Account Holder Name</th>
                <th>IFSC</th>
                <th>Account Number</th>
                <th>Password</th>
                <th>Status</th>
                <th>Remove</th>
                </thead>
                <tbody>
                <tr class="table-active">
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                    <td>8</td>
                    <td>7</td>
                    <td>8</td>
                    <td><button type="button" class="btn btn-primary">approve</button></td>
                    <td><button type="button" class="btn btn-danger">remove</button></td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                    <td>8</td>
                    <td>7</td>
                    <td>8</td>
                    <td><button type="button" class="btn btn-primary">approve</button></td>
                    <td><button type="button" class="btn btn-danger">remove</button></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>

    </div>
</div>
</body>
</html>

ecom_admin/templates/admintemplates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>admin_home</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="row">
        <div class="col-md-2 bg-success nav">
            
            <div>
                <img src="{% static 'images/menwr.jpg' %}" class="admin_img " alt="" style="width: 200px;
                height: 200px;padding-left: 50px;
                padding-top: 50px;
                border-radius: 100px;">
            </div>

            <div class="">
                <ul class="list text-light" style="padding-left: 60px;
                font-size: larger;
                list-style-type: none;">
                    <li><a href="{% url 'ecom_admin:approve_customer' %}" class="li0" style="    text-decoration: none;
                        color: white;">approve_customer</a> </li> <br>
                    <li><a href="{% url 'ecom_admin:approve_seller' %}" class="li0">Approve_seller </a> </li> <br>
                    <li><a href="{% url 'ecom_admin:view_customer' %}" class="li0">View_customer  </a></li> <br>
                    <li><a href="{% url 'ecom_admin:view_seller' %}" class="li0">View_Seller  </a></li> <br>
                </ul>
            </div>
        </div>
    </div>
</body>
</html>

ecom_admin/templates/admintemplates/view_customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View_Cust</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="text-center p-4">
        <h1>VIEW CUSTOMER</h1>
    </div>

    <div class="container">
        <div class="row">
            
            <div class="">
                <table class="table">
                    <thead>
                        <th>Full Name</th>
                        <th>Email</th>
                        <th>Username</th>
                        <th>Phone Number</th>
                        <th>Address</th>
                        <th>Gender</th>
                        <th>Password</th>
                    
                    </thead>
                    <tbody>
                    <tr class="table-active">
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>
                        <td>5</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        
                       
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>
                        <td>5</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        
                       
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    </tbody>
                </table>
            </div>
    
        </div>
    </div>
</body>
</html>

ecom_admin/templates/admintemplates/view_seller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View_Seller</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="text-center p-4">
        <h1>VIEW SELLER</h1>
    </div>

    <div class="container">
        <div class="row">
            
            <div class="">
                <table class="table">
                    <thead>
                    <th>Seller Name</th>
                    <th>Address</th>
                    <th>Phone Number</th>
                    <th>Email</th>
                    <th>Company Name</th>
                    <th>Account Holder Name</th>
                    <th>IFSC</th>
                    <th>Account Number</th>
                    <th>Password</th>
                    
                    </thead>
                    <tbody>
                    <tr class="table-active">
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>
                        <td>5</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        
                       
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>
                        <td>5</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        
                        <!-- <td><button type="button" class="btn btn-primary">approve</button></td>
                        <td><button type="button" class="btn btn-danger">remove</button></td> -->
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    </tbody>
                </table>
            </div>
    
        </div>
    </div>
</body>
</html>