E_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('customer/', include('customer.urls')),
    path('seller/', include('seller.urls')),
    
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

common/urls.py
from django.urls import path
from . import views
app_name='common'
urlpatterns = [
    path('home',views.home, name='home'),
    path('customer_reg',views.customer_reg),
    path('seller_reg',views.seller_reg),
    path('customer_login',views.customer_login, name='customer_login'),
    path('seller_login',views.seller_login,name='seller_login'),
    path('email_exist',views.email_exist, name='email_exist'),

]

seller/urls.py
from django.urls import path
from . import views
app_name = 'seller'
urlpatterns = [
    path('seller_home',views.home,name='seller_home'),
    path('product_cataloges',views.product_cataloges),
    path('add_product',views.add_product),
    path('update_stock',views.update_stock, name='update_stock'),
    path('change_password',views.change_password,name='change_pass'),
    path('recent_order',views.recent_order),
    path('order_history',views.order_history),
    path('profile',views.profile),
    path('seller_signup',views.seller_signup),
    path('get_stock',views.get_stock,name='get_stock'),
]

seller/models.py
from django.db import models
from common.models import Seller

# Create your models here.
class Product(models.Model):
    Seller = models.ForeignKey(Seller,on_delete = models.CASCADE)
    product_name = models.CharField(max_length=70)
    product_description = models.CharField(max_length=100)
    product_number = models.BigIntegerField()
    current_stock = models.IntegerField()
    product_image  = models.ImageField(upload_to='product/')
    price = models.FloatField()

seller/views.py
from django.shortcuts import render,redirect
from common.models import Seller
from .models import Product
from django.http import JsonResponse

# Create your views here.
def home(request):
    Seller_data = Seller.objects.get(id = request.session['seller'])
    return render(request,'sellertemplates/home.html',{'data':Seller_data})



def product_cataloges(request):
    seller_products = Product.objects.filter(Seller = request.session['seller'])
    return render(request,'sellertemplates/product_cataloges.html',{'products':seller_products})




def add_product(request):
    if request.method == 'POST':
            product_name = request.POST['s_productname']
            product_description = request.POST['s_description']
            product_number = request.POST['s_productnumber']
            current_stock = request.POST['s_currentstock']
            product_image  = request.FILES['s_fileupload']
            price = request.POST['s_price']

            new_product = Product(product_name=product_name,product_description=product_description,product_number=product_number,current_stock=current_stock,product_image=product_image,price=price,Seller_id=request.session['seller'])
            new_product.save()
            msg = "product added successfully"
            


    return render(request,'sellertemplates/add_product.html')


def update_stock(request):
    update_stock = Product.objects.filter(Seller = request.session['seller'])
    if request.method == 'POST':
        new_stock =  request.POST['new_stock']
        product_id = request.POST['product_id']
        product = Product.objects.get(id = product_id)
        product.current_stock = product.current_stock + int (new_stock)
        product.save()
    return render(request,'sellertemplates/update_stock.html',{'stock':update_stock})


def change_password(request):
    msg = ''
    if request.method == 'POST':
      

        current_pass = request.POST['crnt_pswrd']
        new_pass = request.POST['new_pswrd']
        confirm_pass = request.POST['cnfrm_pswrd']

        seller_pass = Seller.objects.get(id = request.session['seller'])

        if seller_pass.seller_password == current_pass:
            if new_pass == confirm_pass:
                seller_pass.seller_password = new_pass
                seller_pass.save()
                msg = 'password changed successfully'
            else:
                msg = 'password does not match'
        else:
            msg = 'incorrect password'
            
    return render(request,'sellertemplates/change_password.html',{'msg':msg})


def recent_order(request):
    return render(request,'sellertemplates/recent_order.html')


def order_history(request):
    return render(request,'sellertemplates/order_history.html')


def profile(request):
    seller_profile = Seller.objects.get(id = request.session['seller'])
    return render(request,'sellertemplates/profile.html',{'sprofile':seller_profile})


def seller_signup(request):
    return render(request,'sellertemplates/seller_signup.html')



def logout(request):
    del request.session['seller']
    request.session.flush() # to remove session data from django session table
    return redirect('common:seller_login')


def get_stock(request):
    id = request.POST['id']
    product = Product.objects.get(id=id)
    product_name = product.product_name
    current_stock = product.current_stock
    p_id = product.id
    return JsonResponse({'p_name':product_name,'c_stock':current_stock,'pro_id':p_id})

seller/templates/sellertemplates/add_product.html
{% extends 'commontemplates/common_master.html' %}

{% block content %}

{% load static %}


    <div class="text-center p-4">
        <h1 style="color:  rgb(0, 140, 255);">ADD PRODUCT</h1>
    </div>

    <div class="container bg-light">
        <br>
      <div class="row">
        <div class="col-md-6 p-4">

            <form method="POST" enctype="multipart/form-data">

              {% csrf_token %}
              {{msg}}
                <div class="mb-3">
                  <label for="" class="form-label "><b>Product Name</b></label>
                  <input type="text" name="s_productname" class="form-control" id="" >
                </div>

                <div class="mb-3">
                    <label for="" class="form-label "><b>Description</b></label>
                    <input type="text" name="s_description" class="form-control" id="" >
                </div>

                <div class="row g-3 align-items-center">
                    <div class="col-auto">
                      <label for="" class="col-form-label "><b>Product Number</b></label>
                    </div>
                    <div class="col-auto">
                      <input type="number" name="s_productnumber" id="" class="form-control" aria-describedby="passwordHelpInline">
                    </div>
                </div> <br>


                    <div class="row g-3 align-items-center">
                        <div class="col-auto">
                          <label for="" class="col-form-label "><b>Price</b>&nbsp;&nbsp;</label>
                        </div>
                        <div class="col-auto">
                          <input type="number" name="s_price" id="" class="form-control" aria-describedby="passwordHelpInline">
                        </div>
                    </div> <br>

                    <div class="mb-3">
                        <label for="" class="form-label "><b>Current Stock</b></label>
                        <input type="number" name="s_currentstock" class="form-control" id="" >
                    </div>

                    <div class="mb-3">
                        <label for="" class="form-label"><b>File Upload</b></label>
                        <input type="file" name="s_fileupload" class="form-control" id="" >
                    </div>



                <button type="submit" class="btn btn-primary"><b>Submit</b></button>
            </form>
        </div>

        <div class="col-md-6">
          <img src="{% static 'images/add.jpg' %}" alt="" width="450px" height="400px" style="margin-top: 20px;">
        </div>
      </div>

{% endblock %}

seller/templates/sellertemplates/change_password.html
{% extends 'commontemplates/common_master.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
<div class="container pt-5 pb-5">
    <div class="row">
        <div class="col-lg-12">
            <form method="POST">
                {% csrf_token %}
            
            <div class="card shadow border">
                <div class="card-body">
                    <h3>CHANGE PASSWORD</h3>
                    <form>
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Cureent Password</label>
                        <input type="password" class="form-control" id="exampleFormControlInput1" name="crnt_pswrd">
                    </div><br />
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">New Password</label>
                        <input type="password" class="form-control" id="exampleFormControlInput1" name="new_pswrd">
                    </div><br />
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Confirm Password</label>
                        <input type="password" class="form-control" id="exampleFormControlInput1" name="cnfrm_pswrd">
                    </div><br />
                    
                    <button class="btn-btn">submit</button>
                    {{msg}}
                    </form>
                </div>        
            </div>
        </div>
    </div>
</div>
{% endblock %}

</body>
</html>

seller/templates/sellertemplates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Seller home</title>
    <link rel="stylesheet" href="{% static 'css/sellerhome.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/01741b9219.js"></script>
    <style>
        .div1{
            width: 300px;
        }
        .list-group{
            padding: 20px 20px;
        }
        .list-group a{
            padding: 20px 20px;
        }
    </style>
</head>
<body style="background-color: rgb(70, 123, 154);">
    
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ECOMApp</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <button class="btn btn-outline-success" type="submit"><a href="#">LOGOUT</a></button>
        </div>
    </nav>   
    {% block content %}
   
    {% endblock %}

        <div class="div1">
            
                <div><img src="{% static 'images/seller.jpg' %}" alt="" width="300px" height="300px" style="border-radius: 200px; padding-top:10px;"></div>
            
        

            <div class="list-group" id="id1">
                <a id="a1" href="{% url 'seller:seller_home' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Home</a>
                <a id="a1" href="#" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Catalogue</a>
                <a id="a1" href="#" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Add Product</a>
                <a id="a1" href="#" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Update Stoke</a>
                <a id="a1" href="#" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Change Password</a>
                <a id="a1" href="{% url 'common:seller_login' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Logout</a>
            </div>
        </div>
</body>
<footer>
    <div class="row">
        <div class="col">
            <h3>ECOMApp</h3>
            <p>agdjhskhdlsjklskl;<br>dgshdkjlkd<br>jhddkll;sak;l;.</p>
        </div>
        <div class="col">
            <h3>Office</h3>
            <p>ABC Road</p>
            <p>While Field, ABCD</p>
            <p>Kerala, PIN 673501, India</p>
            <p class="email-id">abcd@gmail.com</p>
            <p>+91 - 01234567</p>
        </div>
        <div class="col">
            <h3>Links</h3>
            <ul>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Clients</a></li>
                <li><a href="#">Awards</a></li>
                <li><a href="#">Blog</a></li>
            </ul>
        </div>
        <div class="col">
            <h3>Newsletter</h3>
            <form action="">
                <i class="fa-regular fa-envelope"></i>
                <input type="email" placeholder=" Enter your email id" required>
                <button type="submit"><i class="fa-solid fa-arrow-right"></i></button>
            </form>
            <div class="social-icons">
                <i class="fa-brands fa-square-facebook"></i>
                <i class="fa-brands fa-square-twitter"></i>
                <i class="fa-brands fa-square-whatsapp"></i>
                <i class="fa-brands fa-square-instagram"></i>
            </div>
        </div>
    </div>
    <hr>
    <p class="copyright">©ECOMApp Ltd 2022</p>
</footer>
</html>

seller/templates/sellertemplates/product_cataloges.html
{% extends 'commontemplates/common_master.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/pswrd.css' %}">
        <div class="row">
            {% for products in products %}
            <div class="col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{products.product_image.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{products.product_name|title}}</h5>
                      <p class="card-text">{{products.product_description}}</p>
                      <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
{% endfor %}
        </div>
                

{% endblock %}

seller/templates/sellertemplates/profile.html
{% extends 'commontemplates/common_master.html' %}
{% load static %}
{% block content %}

<div>
    <img src="{% static 'images/prof.png' %}" alt="" width="400px" height="500px">

    <p>Name: {{sprofile.seller_name}}</p>
    <p>E-mail: {{sprofile.seller_email}}</p>
    <p>Phone: {{sprofile.seller_phone}}</p>
    <p>Address: {{sprofile.seller_address}}</p>
</div>


         
{% endblock %}

seller/templates/sellertemplates/seller_signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>seller signup</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="text-center  p-4">
        <h1>SELLER SIGNUP</h1>
    </div>

    <div class="container bg-success">
        <br>
        <div class="col-md-6 p-4">
            <form>
                <div class="mb-3">
                  <label for="" class="form-label text-light">SELLER NAME</label>
                  <input type="name" name="s_name" class="form-control" id="" >
                </div>

                <div class="mb-3">
                  <label for="" class="form-label text-light" >ADDRESS </label> <br>
                  <textarea name="s_address" id="" cols="30" rows="5" style="width: 400px; border-radius: 10px;"></textarea>
                </div> 

                <div class="row g-3 align-items-center mb-3">
                  <div class="col-auto">
                    <label for="" class="form-label text-light" >PHONE NUMBER</label>
                  </div>
                  <div class="col-auto">
                    <input type="number" name="s_phone" class="form-control" id="">
                  </div>
                  
                </div>

                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label text-light">EMAIL</label>
                    <input type="email" name="s_email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                    <div id="emailHelp" class="form-text"></div>
                  </div>

                  <div class="mb-3">
                    <label for="" class="form-label text-light">COMPANY NAME</label>
                    <input type="text" name="s_company_name" class="form-control" id="" aria-describedby="">
                    <div id="" class="form-text"></div>
                  </div>

                  <div class="mb-3">
                    <label for="" class="form-label text-light">ACCOUNT HOLDER NAME</label>
                    <input type="text" name="s_accholder_name" class="form-control" id="" aria-describedby="">
                    <div id="" class="form-text"></div>
                  </div>

                  <div class="row g-3 align-items-center mb-3">
                    <div class="col-auto">
                      <label for="" class="form-label text-light">IFSC CODE</label>
                    </div>
                    <div class="col-auto">
                      <input type="text" name="s_ifsc" class="form-control" id="" aria-describedby="">
                    </div>
                    <div id="" class="form-text"></div>
                  </div>

                  <div class="row g-3 align-items-center mb-3">
                    <div class="col-auto">
                      <label for="" class="form-label text-light">BRANCH &nbsp;&nbsp;</label>
                    </div>
                    <div class="col-auto">
                      <input type="text" name="s_branch" class="form-control" id="" aria-describedby="">
                    </div>
                    
                    <div id="" class="form-text"></div>
                  </div>

                  <div class="mb-3">
                    <label for="" class="form-label text-light" >BANK ACCOUNT NUMBER</label>
                    <input type="number" name="c_acc_number" class="form-control" id="">
                  </div>


                <div class="row g-3 align-items-center">
                    <div class="col-auto">
                      <label for="inputPassword6" class="col-form-label text-light">PASSWORD</label>
                    </div>
                    <div class="col-auto">
                      <input type="password" name="s_password" id="inputPassword6" class="form-control" aria-describedby="passwordHelpInline">
                    </div>
                    <div class="col-auto">
                      <span id="passwordHelpInline" class="form-text">
                        Must be 8-20 characters long.
                      </span>
                    </div>
                  </div> <br>
                <div class="mb-3 form-check">
                  <input type="checkbox" class="form-check-input" id="exampleCheck1">
                  <label class="form-check-label text-light" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-primary" style="
                color: white;
                height: 40px;
                width: 250px;
                border: none;
                border-radius: 50px;
                box-shadow: 5px 5px 5px rgb(189, 189, 189);">Submit</button>
              </form>
        </div>
    </div>

</body>
</html>

seller/templates/sellertemplates/update_stock.html
{% extends 'commontemplates/common_master.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Stocke</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/01741b9219.js"></script>
    <style>
        .div1{
            margin-top: 100px;
            margin-left: 400px;
            margin-right: 400px;
        }
    </style>
</head>
<body style="background-color:  rgb(70, 123, 154);;">
    <div class="div1">
      <form action="POST" method="POST">
        {% csrf_token %}
        <div class="mb-3">
        <label for="exampleInputProductNumber" class="form-label">Product Number</label>
        <select class="form-select" aria-label="Default select example" id="productno">
          <option value="" selected disabled>selected</option>
          {% for product in stock %}

            <option value="{{product.id}}">{{product.product_number}}</option>
            {% endfor %}
          </select>
          <input type="hidden" id="p_id" name = 'product_id'>
        </div>
        <div class="mb-3">
          <label for="exampleInputproductname" class="form-label">Product Name</label>
          <input type="text" class="form-control" readonly id="productname" aria-describedby="">
        </div>
        <div class="mb-3">
          <label for="exampleInputCurrentStock" class="form-label">Current Stock</label>
          <input type="text" class="form-control" readonly id="CurrentStock" aria-describedby="">
        </div>
        <div class="mb-3">
          <label for="exampleInputNewStock" class="form-label">New Stock</label>
          <input type="number" class="form-control"  id="NewStock" name="new_stock">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>

    <script>
      $('#productno').change(function(){
        $.ajaxSetup({
            headers: {
              "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()  //passing csrf token in ajax request
            }
        })

        $.ajax({
            url:"{% url 'seller:get_stock' %}",  // url in which ajax call is made
            type:'POST',  //method in which data is send
            data:{
                id:$(this).val()  //sending data in json fromat here, key is email
            },
            success:function(response){   
                // console.log(response.p_name)
                // console.log(response.c_stock)
                $('#productname').val(response.p_name)
                $('#CurrentStock').val(response.c_stock)
                $('#p_id').val(response.pro_id)


            }
        })
    })
</script>
    {% endblock %}
</body>
</html>